version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: compose/Dockerfile
    command: /var/www/dev/start.sh

    ports:
      - "8080:80"
    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/var/private-files

      - ../compose/common/config.d:/var/www/config/common.d
      - ../compose/common/lgpd-terms:/var/www/config/lgpd-terms
      - ./config.d:/var/www/config/dev.d

      # themes and plugins
      - ../themes/MapasPA:/var/www/src/themes/MapasPA
      - ../plugins/MapasBlame:/var/www/src/plugins/MapasBlame
      - ../plugins/MultipleLocalAuth:/var/www/src/plugins/MultipleLocalAuth
      - ../plugins/SettingsPa:/var/www/src/plugins/SettingsPa

    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=3
      - JOBS_INTERVAL=3
      
      - APP_MODE=development
      - REDIS_CACHE=redis
      - BUILD_ASSETS=1
      
    depends_on:
      - db
      - redis
      - mailhog

    stdin_open: true
    tty: true

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru  

  db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../compoase/db:/docker-entrypoint-initdb.d
      - ../docker-data/db-data:/var/lib/postgresql/data


  mailhog: 
    image: mailhog/mailhog
    ports:
      - "8025:8025"

